### ISSUE TITLE
For heroku users

### ISSUE THREAD

**Issue by Nirlep5252** [LetsChill/Top.gg-python-webhook-tutorial-#1]
How would I make the webhook work for heroku users? What would I put the URL in the top.gg settings

**Comment by LetsChill** [comment]
i didn’t test it out yet sorry, but it should be the application url that heruko gives you ngl.

**Comment by Nirlep5252** [comment]
I tested that but it doesn't seem to work for me 🤔

**Comment by LetsChill** [comment]
did you change the port to 8080?

**Comment by Nirlep5252** [comment]
hmm, in the code? here are a few screenshots 

https://nirlep-is.a-simp.xyz/23bea5.png
https://nirlep-is.a-simp.xyz/553829.png

**Comment by LetsChill** [comment]
well no idea then, never tried heruko or know how it works ngl as i said before, sorry!

**Comment by Nirlep5252** [comment]
alright np! Thanks anyway
